name: Build Android Binary

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Fairy-Stockfish ARM64
        run: |
          cd src
          NDK_PATH=$ANDROID_NDK_LATEST_HOME
          export PATH="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
          make -j$(nproc) build ARCH=armv8 COMP=ndk CXX=aarch64-linux-android21-clang++

      - name: Upload Android Binary
        uses: actions/upload-artifact@v4
        with:
          name: fairy-stockfish-android-arm64
          path: src/fairy-stockfish
